name: animated_item_picker
description: Generic item picker that encapsulates single or multiple item selection logic.
version: 1.0.3
homepage: https://github.com/kirn-tech/animated_item_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
