name: animated_item_picker
description: Generic item picker that encapsulates single or multiple item selection logic. Based on Column or Row, so it is suitable for fixed size item lists, like custom BottomNavigationBar, week day or gender selector etc.
version: 1.0.0
homepage: https://kirn.tech

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
